### PR TITLE
control ownership on config file

### PR DESCRIPTION
**Pull request by theonewizard**
Added possibility  to set the ownership of the file.

### CODE REVIEW

**Comment by stefangweichinger** [comment]
closes #116

**Comment by theonewizard** [comment]
I think you need to approve my request.

**Comment by stefangweichinger** [comment]
please fix the typos etc mentioned in https://github.com/stefangweichinger/ansible-rclone/pull/117/files

commit your changes then I will approve the test run and if the fixes are OK I can merge your PR

**Comment by theonewizard** [comment]
I do not see any comments but I see a few spellings errors. If that is it I will fix it later.

**Comment by stefangweichinger** [comment]
1. "allow", not "allows"
2. "than", not "then"
3. Third sentence: I'd remove it.

That's the 3 comments I added there. Unsure if you can see them. Seems not.

**Comment by theonewizard** [comment]
Hi

Thanks, now I see it. Sorry if I offended you, it was not my intention.
Thanks for making the role, it has helped me a lot.

**Comment by stefangweichinger** [comment]
You're welcome. I am a bit busy these days, plus holidays and stuff, so please be patient, I will merge your PR as soon as I find the time. I try to look twice before merging PRs to not break things etc. Glad to hear that the role helps, thanks for improving it.

**Comment by stefangweichinger** [comment]
I did some fixes to the README, but had merged too soon ... that's what caused the merge-revert-merge action above.

If you want to improve things even more: it would be great to improve the molecule checks of the role and check installing with a specific config_owner setting (although the test wouldn't be very meaningful maybe: a chown should work ...). Just a thought.

That would go into a new PR then, sure ;-)

**Pull request merged**
