### PR TITLE
new Fedora 32 release: test and support

### PR DESCRIPTION
**Pull request by stefangweichinger**

### CODE REVIEW

**Comment by triwats** [comment]
The systemd stuff is still so annoying! 😭

**Comment by stefangweichinger** [comment]
> The systemd stuff is still so annoying!

I can't follow. What systemd stuff?

**Comment by triwats** [comment]
@stefangweichinger 

This kinda stuff:

```
  - name: fedora32
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-fedora32}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
```

A necessary evil

**Comment by stefangweichinger** [comment]
Yes. Although I don't like `privileged` here: it crashes my Fedora Workstation when I run molecule tests ... the current `molecule.yml` does disable that. This has to be solved somehow. Maybe some clever detection of "is it travis or not?".

**Comment by stefangweichinger** [comment]
came up with #55 : looks promising to me

**Pull request merged**
