### PR TITLE
Ensure local mount path exists

### PR DESCRIPTION
**Pull request by tigattack**
Adds a task to ensure the local mount path exists with optionally configurable mode, owner, and group.

### CODE REVIEW

**Comment by tigattack** [comment]
Should this new task respect the state of `rclone_mkdir`? I think not, since I can't envisage a scenario where a user would not wish for the local mount path to exist, but can imagine some users may wish to be more stringent when it comes to performing actions on the remote filesystem (hence why `rclone_mkdir` exists, I suppose).

Open to thoughts/discussion.

**Comment by stefangweichinger** [comment]
@tigattack thanks for your PRs. Pls allow me some time until I can look into and think about them. Busy days here ;-)

**Comment by stefangweichinger** [comment]
sorry for being so late here. busy times

**Comment by stefangweichinger** [comment]
I have no specific opinion here. I like the enhancement and tend to merge it to get the PR closed at last (my fault).
I assume you, @tigattack use your patched version since filing this PR ... so it's "tested" already.

A new release to galaxy needs a tag anyway, I might wait with tagging until I am through the other PRs.

**Comment by tigattack** [comment]
No problem, I understand! Indeed, I have been using my patch and it seems to be working great.

**Pull request merged**
