### PR TITLE
improved handling of local_facts, fix test for binary installation

### PR DESCRIPTION
**Pull request by stefangweichinger**

### CODE REVIEW

**Comment by theenglishway** [comment]
:wave: 

I've given it a try : it seems to do the job when it comes to compatibility with older Jinja2 version (tested with 2.10.3).

But there seems to be some `become: true` missing, because I get a "permission denied" on task "Remove temporary working directory" (this directory belongs to root and the task removing it does not 

Steps to reproduce: 

1. install the stable version of rclone (v1.54.1) using your role
2. set rclone_version to 1.54.0
3. run your role

Since the whole install-bin.yml is doing root stuff, I would put `become: true` in the include task, like that : 

```
- name: Install the binary
  include_tasks: install-bin.yml
  **become: true**
  when: (((not ansible_local.rclone.installed|d())|bool) or (ansible_local.rclone.installed_version|d("0.0.0")) != rclone_version)
```

**Comment by stefangweichinger** [comment]
I will try in the branch "issue83".

**Comment by stefangweichinger** [comment]
The installation of the config could be written as a block within `main.yml` and that block would have one `become` statement.
just a second

**Comment by stefangweichinger** [comment]
pls test that one / I am afk for an hour now.

**Comment by stefangweichinger** [comment]
@theenglishway Do you think you could test this latest version before I merge? It would make me more confident ;-) thanks

**Comment by theenglishway** [comment]
I will, but I can't promise I will do it before the end of the week !

**Comment by stefangweichinger** [comment]
Thanks

**Pull request merged**
