### PR TITLE
some debugging around issue #66

### PR DESCRIPTION
**Pull request by stefangweichinger**

### CODE REVIEW

**Comment by stefangweichinger** [comment]
7ee76a226a5558c0ee651fe1cac8737856d578bb fixes the tests

dd6fcdfeb5346a8698650ff34e1b3762f4d10718 corrects the test matrix, `rclone_version` would be always preset otherwise

**Comment by stefangweichinger** [comment]
I think we have to clear the directory `rclone_setup_tmp_dir` either before the unarchive task or at least in the molecule runs: otherwise in the test runs there already exists a extracted archive in that dir and your comparison fails.

I think it would be the easiest to just scratch that dir every time. The speed gain isn't important here, and it makes things more robust.

**Comment by stefangweichinger** [comment]
I assume the latest fails relate to the upstream issue at the rclone-beta-repo.

@mjmayer : pls have a look and thought at the two uses of

```
when:
  - rclone_version | length == 0
```

**Comment by mjmayer** [comment]
> I assume the latest fails relate to the upstream issue at the rclone-beta-repo.
> 
> @mjmayer : pls have a look and thought at the two uses of
> 
> ```
> when:
>   - rclone_version | length == 0
> ```

`rclone_release` is default as stable. If `rclone_version` is left at the default of `""`, then the playbook will look up the latest version and download that version. If `rclone_version` is provided, the playbook will skip looking up the latest version.

I saw some comments that ansible-lint doesn't like comparisons to empty strings. The suggested work around I found was `rclone_version | length == 0`. This should have the same effect.

**Comment by stefangweichinger** [comment]
> > I assume the latest fails relate to the upstream issue at the rclone-beta-repo.
> > @mjmayer : pls have a look and thought at the two uses of
> > ```
> > when:
> >   - rclone_version | length == 0
> > ```
> 
> `rclone_release` is default as stable. If `rclone_version` is left at the default of `""`, then the playbook will look up the latest version and download that version. If `rclone_version` is provided, the playbook will skip looking up the latest version.
> 
> I saw some comments that ansible-lint doesn't like comparisons to empty strings. The suggested work around I found was `rclone_version | length == 0`. This should have the same effect.

Thanks for the explanation, I understand the intention.
But the logic doesn't work yet fully, check the failing tests.

rclone_version wasn't rewritten in the block in `tasks/stable.yml`, so this resulted in trying to download a misnamed archive.

I can't find the failing test right now, did you rerun some jobs maybe?

I'll try to get an up2date overview asap, busy right now.
And I'd maybe like to wait for the upstream bug to be fixed before merging these changes here.

**Comment by stefangweichinger** [comment]
@mjmayer I readded that when-clause again above, now that the upstream issue has been solved (for now ...) all tests run through. Maybe you can have an additional look as well, before I merge this into master.

Unfortunately my workflow already released this branch code as role to galaxy :-(  not intended ... I have to figure out how to run the molecule tests for all branches, but only publish the master branch. I hope I didn't break things for people.

**Comment by stefangweichinger** [comment]
@mjmayer Ah, one more: we have a linting issue in  `tasks/beta.yml` :

``` 
18:141    warning  line too long (155 > 140 characters)  (line-length)
```

suggestions? Or should I allow longer lines in the linting-config?
Thanks!

**Comment by mjmayer** [comment]
> @mjmayer Ah, one more: we have a linting issue in `tasks/beta.yml` :
> 
> ```
> 18:141    warning  line too long (155 > 140 characters)  (line-length)
> ```
> 
> suggestions? Or should I allow longer lines in the linting-config?
> Thanks!

I tried to figure out how to split the line into multiple lines and I couldn't figure it out. It is just a warning. I would just let it be.

**Comment by stefangweichinger** [comment]
> I tried to figure out how to split the line into multiple lines and I couldn't figure it out. It is just a warning. I would just let it be.

I have a suggestion, lint is happy here on my box, see 13511c7
Yes, only a warning. But it's nice to have it as clean as possible ;-)

**Comment by stefangweichinger** [comment]
I thought I had a solution but it failed. This should be another issue then .. (2 linters active right now, and the long line with one long variable in it).
I reverted the patch and would merge this PR as soon as the tests ran through? I rely on your review here ;-)
Thanks for contributing!

For sure this still isn't *solved*, the upstream build issue still exists.

**Comment by stefangweichinger** [comment]
We don't yet have an example for setting a specific version in `README.md`.
I might add that later and then merge.

**Comment by stefangweichinger** [comment]
fixes #66 and #68: set specific version to install, added check task to catch edge case with beta releases

**Comment by stefangweichinger** [comment]
@mjmayer  Yes, issue closed. 
An additional idea for an improvement:

I'd like to check the version within molecule's `verify.yml` as well.
Are you interested in working on this as well? just an idea

**Comment by mjmayer** [comment]
There is already a check for the version in the playbook. This could be easily duplicated to run in the molecule test as well. On a failure, when the version downloaded doesn't match the version expected, the assert in `verify.yml` will probably never get ran, since the playbook failed.

**Comment by stefangweichinger** [comment]
Sure, I know about that check ;-)

It's not that easy to just use that in `verify.yml`, because the values of the parameters aren't all available in the molecule playbooks. Hard to describe in short, but I noticed this when writing that verifier. Maybe I just start a new issue for that ... it's more of a "learning how to use molecule" issue, afaik.

**Pull request merged**
