### PR TITLE
feat: add support for Archlinux

### PR DESCRIPTION
**Pull request by gamezftw**
Molecule scenario for Archlinux has different configuration so that is why it is separated from the default one.

### CODE REVIEW

**Comment by stefangweichinger** [comment]
@gamezftw thanks for your contribution. Will look into it asap.

**Comment by stefangweichinger** [comment]
wow, that's quite some patchset ;-) looking forward to read and understand

**Comment by stefangweichinger** [comment]
linting fails ... maybe the checkout is missing from your new scenario .. ?

**Comment by gamezftw** [comment]
It looks like that those files should have been excluded from ansible-lint like the ones from the default scenario. It is now updated with the last commit 3040f82562a25727d6d7b21592aab93bd85b0d81

**Comment by stefangweichinger** [comment]
Hmm, yes. This should be fixed maybe, so that these files also get linted etc

This is a different issue than your PR, sure.

Aside from that I have to look at some details.

**Comment by stefangweichinger** [comment]
Your archlinux tests should be named accordingly.

Right now (example):

"(default, debian12, stable, archlinux, archlinux) (pull_request) "

That shouldn't be "debian12" in the 2nd field, right? thanks for checking

**Comment by gamezftw** [comment]
There was no need to run archlinux scenario for each of other distros so I've split it in a new job 4e96d97cbf0b5da68d6774a1e0ce9b927b216ab0 . I am not sure if there is a better way to do this to avoid duplication but let's see if this is ok for now.

**Comment by stefangweichinger** [comment]
> There was no need to run archlinux scenario for each of other distros so I've split it in a new job [4e96d97](https://github.com/stefangweichinger/ansible-rclone/commit/4e96d97cbf0b5da68d6774a1e0ce9b927b216ab0) . I am not sure if there is a better way to do this to avoid duplication but let's see if this is ok for now.

Thanks for the commit. I don't know right now either.

Maybe we add some note to the README also (I can do that), and then I would merge.

**Comment by gamezftw** [comment]
Do you know why release is failing https://github.com/stefangweichinger/ansible-rclone/actions/runs/9461553345/job/26063478191?pr=151 ? Is something wrong with api key https://github.com/stefangweichinger/ansible-rclone/blob/2aec630547fe4e49dfee244cd3a1c094a2e5faef/.github/workflows/molecule.yml#L75C11-L75C25 ?

**Comment by stefangweichinger** [comment]
@gamezftw release only happens in branch `main`. but yes, I had issues with the API key several times and released manually a few times. Sorry for not finding time to process this PR currently.

**Comment by stefangweichinger** [comment]
> Do you know why release is failing https://github.com/stefangweichinger/ansible-rclone/actions/runs/9461553345/job/26063478191?pr=151 ? Is something wrong with api key https://github.com/stefangweichinger/ansible-rclone/blob/2aec630547fe4e49dfee244cd3a1c094a2e5faef/.github/workflows/molecule.yml#L75C11-L75C25 ?

IMO the used [docker-image](https://github.com/robertdebock/docker-github-action-galaxy) is broken and calls `ansible-galaxy` with wrong options. This should be fixed upstream, I am currently unsure how to proceed. Might create a separate issue for this.

**Comment by stefangweichinger** [comment]
@gamezftw I think I fixed the release-issues in a38881d
Could you rebase your patches, pls? I am unsure how I can do that within the GUI here. Thanks!

**Comment by stefangweichinger** [comment]
we should also consider adding arch to `galaxy_info` in `meta/main.yml`

**Comment by stefangweichinger** [comment]
Managed the rebase myself, I think.
Your PR will go into 0.1.7 I assume ...
0.1.6 just went online: https://galaxy.ansible.com/ui/standalone/roles/stefangweichinger/ansible_rclone/

**Comment by stefangweichinger** [comment]
May I be picky?
We should update your molecule task as well:

* use checkout@v4 action
* use latest molecule action
* test against rclone-1.67.0

check a38881d for reference, I upgraded these things today

thanks, this will also use latest stuff in the archlinux-scenario

**Comment by gamezftw** [comment]
```
platforms:
    - name: ArchLinux
      versions:
        - 'all'
```
`all` should be ok since it is rolling-release

**Comment by gamezftw** [comment]
Action versions and metadata stuff is updated now too.

Also requirements.txt molecule version is updated to match the one for the action from here https://github.com/robertdebock/docker-github-action-molecule/commit/70aa9b1c474a2412c64d071148d45b7217da550b

**Comment by stefangweichinger** [comment]
looks great. release step failing, I am not sure if it fails only while not on `main` branch. Will try to merge and release today.
thanks @gamezftw

**Comment by gamezftw** [comment]
Happy to help!

Do you think we should add condition for `release` to not run on a PR? Or we can have separate workflows where one would run on a PR and do tests and another one when code is pushed to main branch which would do release?

**Comment by stefangweichinger** [comment]
> Do you think we should add condition for `release` to not run on a PR? Or we can have separate workflows where one would run on a PR and do tests and another one when code is pushed to main branch which would do release?

Sure. I was under the impression that it's configured that way already.
Several things mix here:

* the error message points at the (missing) api key again: that was fixed in `main` last week by using the "right" gh-action-release for "robertdebock/molecule-action", afai understood.
* is the api key defined in the repo? yes, did set the secret accordingly last week
* the definition of the gh-action or better the workflow: "do things only in main branch"

Right now the action is called without the variable set somehow when running in the PR branch.

**Comment by stefangweichinger** [comment]
I rebased and merged now. This should test ok in `main`.
For the release step to work there needs to be a new tag on the latest commit then. `commitizen` should do that somehow, for the last releases I always tagged it manually (will do in a minute).

**Comment by stefangweichinger** [comment]
Hm, unfortunately there's one error:

https://github.com/stefangweichinger/ansible-rclone/actions/runs/9973604917/job/27559320038#step:5:191

unsure right now

0.1.7 was released though (because the workflow isn't 100% correct :-P )

The whole testing and releasing is more complicated already than the actual installing of `rclone` ;-)

**Comment by stefangweichinger** [comment]
> Happy to help!
> 
> Do you think we should add condition for `release` to not run on a PR? Or we can have separate workflows where one would run on a PR and do tests and another one when code is pushed to main branch which would do release?

Suggestions welcome here. Would love to improve that before merging the next PRs. I am a bit busy in these days and don't have much time for researching this. If you are willing to suggest something, pls open a new issue for this topic.

**Pull request merged**
