### PR TITLE
Add support for rclone.conf file, now with passing tests

### PR DESCRIPTION
**Pull request by jackodsteel**
Exact same PR as #31 except now I have fixed the failing tests which were just linting errors.

I've ran all the tests and confirmed they pass now.

### CODE REVIEW

**Comment by jackodsteel** [comment]
Also note if you want to check out my changes to run the tests yourself you should be able to do something like this rather than having to merge it into a different branch in your repo first:

https://stackoverflow.com/a/14773085/12028955

**Comment by stefangweichinger** [comment]
https://travis-ci.org/stefangweichinger/ansible-rclone/builds/614854664  looks good now, seems I did check the wrong spot yesterday. Now let's merge this again. Thanks!

**Comment by stefangweichinger** [comment]
@jackodsteel  Could you maybe add some more example `rclone_configs` ? To me the example with the google drive isn't fully understandable and I think it would be great to give 2 or 3 working examples for maybe a WebDAV share or rsync. Maybe you have something at hand (and put it into a next PR or add it here?). thanks.

**Comment by stefangweichinger** [comment]
Ad failing tests: I should have looked here:

https://travis-ci.org/stefangweichinger/ansible-rclone/builds/613910458

**Pull request merged**
