### PR TITLE
Improvements to mount tasks & related docs

### PR DESCRIPTION
**Pull request by tigattack**
* Define more relevant loop labels for mount tasks
* Document `rclone_mkdir`

### CODE REVIEW

**Comment by stefangweichinger** [comment]
sorry for being so late here. busy times

**Comment by stefangweichinger** [comment]
quick look: ok to me ... *but* the molecule-tests don't test this, right?

Shouldn't we maybe add some test(s) for that also?

**Comment by stefangweichinger** [comment]
Sounds to be rather complicated. `local` would be a local directory in the target machine (in terms of testing here: target docker container)? hm, that might be possible to realize.

I am not sure if it's necessary or goes beyond the scope here.

**Comment by tigattack** [comment]
Given the simplicity of the implementation, I'd personally be happy without a test in this case. 

I think if we were to test this, it would open the door to test many other configurable/non-default aspects of the role. While that certainly wouldn't be a bad thing, I think this would fall rather low in the list of priorities if we were to add further tests.

**Comment by stefangweichinger** [comment]
I tagged 0.2.1 now ... should result in a release to galaxy.
If #161 is correct etc

**Pull request merged**
