### PR TITLE
Add support for rclone.conf file

### PR DESCRIPTION
**Pull request by jackodsteel**
Using a j2 template to create rclone.conf file from ansible variables.

### CODE REVIEW

**Comment by stefangweichinger** [comment]
thanks @jackodsteel for your PR, will look into it in the next days

**Comment by stefangweichinger** [comment]
I screwed ths PR up, would you mind re-opening or editing this PR to merge it into the branch https://github.com/stefangweichinger/ansible-rclone/tree/test_PRs ? thanks!

(unfortunately I noticed the molecule test breaking after merging ...)

**Comment by stefangweichinger** [comment]
gh doesn't allow my to re-open this PR, I don't know why

**Comment by jackodsteel** [comment]
I don't think you can reopen a merged PR. I'll make a new one.

**Pull request merged**
