### PR TITLE
GPG verify stable rclone

### PR DESCRIPTION
**Pull request by ClashTheBunny**
This downloads the SHA256SUMS and the GPG key of the author (which I sure hope is right!) and verifies the download.  This is good for security, but also integrity of the download.  I only did this on the stable side of things, I'm not sure if the betas are similarly signed and verified.

### CODE REVIEW

**Comment by stefangweichinger** [comment]
thanks @ClashTheBunny for the PR, looks promising. Will look into it into more detail in a few days.
ansible galaxy complained about the failing import, I have to check where that came from etc

**Comment by ClashTheBunny** [comment]
Fixed a bug when there isn't a gpg keychain yet, this may be the problem in ansible galaxy.  Also, most things aren't available during `check` mode, so I marked those parts such that it will get through a check without erroring out.

I did poke around trying to find the SHA265SUMS for the beta and nothing seems to exist.  I'm asking in https://github.com/ncw/rclone/issues/1449 to see if there is an option for getting that verified also.

**Comment by stefangweichinger** [comment]
> Fixed a bug when there isn't a gpg keychain yet, this may be the problem in ansible galaxy. Also, most things aren't available during `check` mode, so I marked those parts such that it will get through a check without erroring out.
> 
> I did poke around trying to find the SHA265SUMS for the beta and nothing seems to exist. I'm asking in [ncw/rclone#1449](https://github.com/ncw/rclone/issues/1449) to see if there is an option for getting that verified also.

great, thanks. Sorry for missing replies, very busy right now.

**Comment by stefangweichinger** [comment]
@ClashTheBunny  do you have any more news coming here or does this PR work as intended?

**Comment by stefangweichinger** [comment]
I screwed up this PR, would you mind re-opening or editing this PR to merge it into the branch https://github.com/stefangweichinger/ansible-rclone/tree/test_PRs ? thanks!

(unfortunately I noticed the molecule test breaking after merging ...)

**Comment by stefangweichinger** [comment]
gh doesn't allow my to re-open this PR, I don't know why

**Pull request merged**
