### PR TITLE
Revert "Rewrite download section to automatically get the latest version."

### PR DESCRIPTION
**Pull request by stefangweichinger**
Reverts stefangweichinger/ansible-rclone#19
Breaks current travis tests.

### CODE REVIEW

**Comment by stefangweichinger** [comment]
breaks current tests. Maybe you could test against the new molecule tests mentioned in #20 ?
I am planning to merge them into master asap.

**Comment by PaddyTheShamrock** [comment]
I think they are all failing because the current tests try to run /user/sbin/rclone, but my code installs rclone to /usr/bin/rclone as per the installion recommendation at [https://rclone.org/install/](url). I don’t know much about molecule, are you happy to adjust the tests?

**Comment by stefangweichinger** [comment]
sure. I am learning to use molecule as well and will try to test your PR locally before pushing.

**Comment by stefangweichinger** [comment]
@PaddyTheShamrock sorry for messing up the PRs here, I have to get used to the workflow in here.
I am way more admin than coder.

pls look at https://github.com/stefangweichinger/ansible-rclone/tree/pr20 ... that branch should contain your PR #19 and my new molecule tests.

Tests look OK locally and on travis: https://travis-ci.org/stefangweichinger/ansible-rclone/builds/493967072

**Comment by PaddyTheShamrock** [comment]
No worries, I’m learning too😊. The pr20 branch seems to be the code from before my pull request and your commit of it. You’ve committed the pull request to master instead, so it’s that that will need to pass molecule tests.

**Comment by stefangweichinger** [comment]
Ah, I see. OK. I rebuild and enhance the molecule tests now in branch pr20 (misnamed again ...)
Maybe you could re-pull the pr20 branch and file a new PR with your changes on top of that.

Or we wait until I merged my new tests into master and you do your PR based on that ;-)

I definitely would prefer to move the related conversation over to a new open PR.

**Comment by stefangweichinger** [comment]
@PaddyTheShamrock  #22 now

**Comment by stefangweichinger** [comment]
@PaddyTheShamrock pls comment asap, I want to merge #22 soon. Unfortunately I mixed up your and my changes into that one PR ... if you prefer to show up in the contributors list I will have to take another look and split it into 2 PRs or so. thanks.

**Comment by PaddyTheShamrock** [comment]
@stefangweichinger sorry, been away with family. I've read over #22  it looks good to me. I think my PR got merged into master, and then this branch was created? As you say, my changes are integrated already, so not much else for me to do. I think it would be too much work to separate them now, so go ahead and merge as one. I'll probably look at making the beta version selectable soon, so I'll make the contributors list next time ;)

**Comment by stefangweichinger** [comment]
@PaddyTheShamrock thanks. next PR I will do better (I hope).
#22 merged, master tests run on Travis
looking forward to new PRs, I have ideas as well.

**Pull request closed without merging**
