### PR TITLE
ensure no sbin/rclone exists.

### PR DESCRIPTION
**Pull request by anordin95**
The latest version of this ansible-role installs rclone to usr/bin. Previous versions installed to /usr/sbin. The path on our machines were set to look into /usr/sbin prior to /usr/bin causing version inconsistencies. This change introduces a task to ensure no rclone exists in /usr/sbin.

### CODE REVIEW

**Comment by stefangweichinger** [comment]
That was changed in commit 3e52131c1f66ffd90d52a29a8f229daa1c636de6 ... about one year ago.

I am unsure if the role should remove `/usr/sbin/rclone`, that seems a bit too "aggressive" to me.
Maybe we should do the test but only *warn* and let the user decide?

**Comment by anordin95** [comment]
You're right. It does feel a bit aggressive. I jumped towards that solution, because it fits my use-case well. Do you have a suggestion on a simple way to go about prompting the user like that?

I didn't see a flag in the `file` module from Ansible to do so. I'm a bit new to Ansible as well. What would you suggest in the way of building that functionality?

**Comment by drybjed** [comment]
Allow me to add another perspective...

I see that you changed the install path from `/usr/sbin/rclone` to`/usr/bin/rclone`. This is a one time change, I guess the prior installation was a mistake and you want to rectify it.

Keep in mind that `/usr/sbin/rclone` might not be "your" installation of `rclone`, especially that you don't seem to use the OS packages to install it. So, instead you should install it as `/usr/local/bin/rclone`. As for @anordin95 issue about wrong `rclone` version... Customarly I saw that the
`/usr/local/bin` path is usually first in `$PATH`, so the `rclone` installed there should "take over" the duties of `rclone` installed from the OS packages if one happens to be on the system.

If you are concerned that the wrong version of `rclone` is used, you should specify the full path to the desired version instead of removing random binaries from `/usr/sbin/`. That way you can always be sure that the desired version is executed and don't rely on "random" order of paths in `$PATH`.

**Comment by stefangweichinger** [comment]
thanks @drybjed !

**Comment by stefangweichinger** [comment]
So for me it seems we should change the path to `/usr/local/bin/rclone` ?
And *not* remove any other installation of `rclone` as I suggested before.

I think it would be useful to add a testing task to the role: if any other rclone-binary is found on the target system, we should inform/warn the user.

**Comment by anordin95** [comment]
Yep, working on it.

**Comment by stefangweichinger** [comment]
> Yep, working on it.

Thanks, looking forward to your PR.
The path-change is trivial ...

**Comment by anordin95** [comment]
Yep. I'm trying to test on a linux machine first, and the VPN I need to ssh in is down.

**Comment by stefangweichinger** [comment]
@anordin95  see #42 : I am fixing and enhancing the molecule tests now, that PR will also edit the installation path.

Better wait for #42 being merged and base your PR on the updated master then.

**Comment by anordin95** [comment]
Example output
image

**Comment by stefangweichinger** [comment]
thanks! looks quite good.
Now look at the travis test, for example here:
https://travis-ci.org/stefangweichinger/ansible-rclone/jobs/656322977

You have formatting issues in main.yml, trailing spaces in lines 49,54,56 ;-)
If you commit a corrected file, travis/molecule might succeed then.

**Comment by anordin95** [comment]
I don't have merge perms. I presume this is good to go, but let me know if not.

**Comment by stefangweichinger** [comment]
> I don't have merge perms. I presume this is good to go, but let me know if not.

The code is OK; but I am still discussing if I want that behavior in the role with another role-dev.

**Comment by anordin95** [comment]
Ah, fair enough.

**Comment by stefangweichinger** [comment]
I think I don't want a warning. 

If there is a binary installed from the OS-repos it goes into `/usr/bin` (I refer to Debian here: https://packages.debian.org/buster/amd64/rclone/filelist ).

As the role installs into `/usr/local/bin` now there is no problem with overwriting or so, it just installs that second binary and it is up to the user to select at run-time, by defining the absolute path or setting `$PATH` in the environment of his scripts etc.

I don't want to overwrite or remove a binary that has been installed via the OS package manager, this seems to "aggressive" to me. And a warning ... ansible is around automation, so it mostly should run without interaction. I prefer to maybe explicitly *document* what we do and what not and let the user decide on his own how to break his machine(s) ;-)

Another option might be adding some new boolean toggle or so to allow detecting and/or rm-ing existing binaries of `rclone`. But in my opinion that's a bit over the top, maybe?

Feedback welcome!

**Comment by anordin95** [comment]
To recap:
The current install location is: `/usr/local/bin/rclone`
A long time ago (1+ year) the install location was: `/usr/sbin/rclone`. 

Apparently, it's common for `/usr/local/bin/` to come before `/usr/sbin/` in `$PATH`. Thus, a warning feels a bit unnecessary. My fear would be `/usr/sbin` coming before `/usr/local/bin` and thus the user silently using an old installed version of rclone.

I agree that this warning feels unnecessary! It would make sense to me to close this.

**Comment by stefangweichinger** [comment]
@anordin95 thanks for your code and the discussion.
I close this PR unmerged, maybe #44 will include a more detailed handling then.
If the role adds installation from OS repos (think of signed packages and security ...) it also will have to do more checks maybe.

**Pull request closed without merging**
