### PR TITLE
Add check_mode: no to allow --check-mode to succeed

### PR DESCRIPTION
**Pull request by danrabinowitz**

### CODE REVIEW

**Comment by stefangweichinger** [comment]
thanks for the PR, unfortunately it breaks the tests. I assume you want to register a variable, then you seem to need another TAB in front maybe. Please also explain what this change does. thanks

**Comment by danrabinowitz** [comment]
I fixed the tests.

Without this PR, anyone using this role cannot run their playbooks in "check" mode.

It is useful to run
```sh
ansible-playbook --check
```
before running
```sh
ansible-playbook
```

By running with --check first, you can see what the playbook would do, before you actually run the playbook without --check.

This PR is needed to allow the role to work with --check.

Basically, this PR tells ansible to run the task normally, even if in check mode. This is safe because the task doesn't actually do anything except register a variable. And this is necessary because the role can not continue without the registered variable, even in check mode.

**Comment by stefangweichinger** [comment]
Nice one, thanks. Do you think we should add your explanation to the main README (documenting stuff ...) or is it self explaining to the people knowing that "--check" option?

**Comment by danrabinowitz** [comment]
I don't think there's any reason to document it. In "normal" mode it doesn't change anything. And in "check" mode it just works correctly. So I don't think there's anything to document.

**Comment by stefangweichinger** [comment]
thanks, closed

**Pull request merged**
